### PR TITLE
Rebase onto the latest master

### PR DESCRIPTION
**Pull request by Abestanis**
I rebased the `patch` branch on the latest upstream `master` branch & added one commit to fix the build (https://github.com/Abestanis/FlutterToast/commit/a5ab337bf39473964c629297049173dda3d12763)

This was necessary to update Flutter.

Not sure how to proceed here. Ideally we would get this merged into upstream. Do you want me to try and do that?

In the mean time, do we want to replace the `patch` branch with this one so we can update Sweyer, or should we just point it to my branch?

### CODE REVIEW

**Comment by Abestanis** [comment]
I created https://github.com/ponnamkarthik/FlutterToast/pull/519 to hopefully land the font asset changes upstream.

In the meantime, we should decide if we want to switch Sweyer in https://github.com/nt4f04uNd/sweyer/pull/130 to this branch in my fork, or if you want to merge this into your branch.

**Comment by Abestanis** [comment]
This is no longer needed now that https://github.com/ponnamkarthik/FlutterToast/pull/519 got merged and a new version got released! 🎉

**Comment by nt4f04uNd** [comment]
It's a bit amusing I never even noticed this PR 💀
(because of switched off notifications on forks by default)

Sorry!
The amount and quality of your contributions is far beyond of what I can process these times

**Comment by Abestanis** [comment]
> The amount and quality of your contributions is far beyond of what I can process these times

Thank you @nt4f04uNd, that means a lot!

I also appreciate the time you take to review all of these, I know that that's not easy and I am more than happy to wait for a review, so please don't feel rushed.

**Pull request closed without merging**
